/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Finding total customers by Countries.
SELECT
country,
count(customer_key) AS Total_customers
from gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC


-- Find total customers by gender
SELECT
gender,
count(customer_key) AS Total_customers
from gold.dim_customers
GROUP BY gender
ORDER BY Total_customers DESC


-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
from gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category 
SELECT 
category,
AVG(cost) AS Avg_cost
from gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC


-- What is the total revenue generated for each Category
SELECT
p.category,
SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC

-- Find total revenue is generated by each customer 
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_revenue DESC

-- What is the distribbution of sold items across countries
SELECT
c.country,
SUM(f.quantity) AS Total_sold_item
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
GROUP BY 
c.country
ORDER BY Total_sold_item DESC
 